sn create: code & test

diff --git a/sn b/sn
--- a/sn
+++ b/sn
@@ -4,13 +4,42 @@ set -eu
 
 # include lib/utils.sh
 
+main() {
+	cmd=$1
+	shift
+
+	mkdir -p "${SN_DATA:=$HOME/.sn}"
+
+	case $cmd in
+		create)
+			cmd_create "$1"
+		;;
+
+		*)
+			die "Invalid command"
+		;;
+	esac
+}
+
 usage() {
 	echo "usage: ${0##*/} <command>"
 	exit 1
 }
 
-cmd_create() {
-	# local cfg = $1
+die() {
+	echo "Error: $1" >&2
+	exit 1
 }
 
+cmd_create() {
+	dir=${SN_DATA}/$1
+	mkdir -p "$dir" || die "Creating social network directory"
+	cd "$dir" || die "Unable to change into directory"
+	git init
+}
 
+cmd_join() {
+	true
+}
+
+main "$@"
diff --git a/tests/local-workflow b/tests/local-workflow
--- a/tests/local-workflow
+++ b/tests/local-workflow
@@ -1,11 +1,31 @@
 #!/bin/sh
 
+sn="$(dirname "$(dirname "$0")")/sn"
+
 setup() {
-	true
+	mkdir -p "$ts_test_dir"
+	export SN_DATA="$ts_test_dir"
 }
 
-test_true() {
-	true
+teardown() {
+	rm -r "$ts_test_dir"
 }
 
-. bin/ts
+error() {
+	echo "Error: $1"
+	exit 1
+}
+
+test_invalid_command() {
+	$sn invalid-command
+	assert_status 1 $?
+}
+
+test_create() {
+	$sn create test-social-network
+	assert_status 0 $?
+	[ -d "$SN_DATA/test-social-network/.git" ] \
+		|| error "Git repository not initialized"
+}
+
+. tests/ts
